export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  salary: string;
  type: "Full-time" | "Part-time" | "Contract" | "Remote" | "Internship";
  experience: string;
  category: string;
  description: string;
  requirements: string[];
  postedDate: string;
  logo?: string;
  featured?: boolean;
}

export const categories = [
  { id: "it", name: "IT & Software", icon: "Monitor", count: 2450 },
  { id: "finance", name: "Finance & Accounting", icon: "IndianRupee", count: 1820 },
  { id: "marketing", name: "Marketing & Sales", icon: "TrendingUp", count: 1560 },
  { id: "engineering", name: "Engineering", icon: "Settings", count: 2100 },
  { id: "healthcare", name: "Healthcare", icon: "Heart", count: 980 },
  { id: "education", name: "Education", icon: "GraduationCap", count: 750 },
  { id: "design", name: "Design & Creative", icon: "Palette", count: 620 },
  { id: "hr", name: "HR & Recruitment", icon: "Users", count: 540 },
] as const;

export const locations = [
  "Mumbai",
  "Delhi NCR",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  "Noida",
  "Gurgaon",
  "Remote",
];

export const experienceLevels = [
  "Fresher",
  "0-1 years",
  "1-3 years",
  "3-5 years",
  "5-10 years",
  "10+ years",
];

export const sampleJobs: Job[] = [
  {
    id: "1",
    title: "Senior Software Engineer",
    company: "TechMahindra",
    location: "Bangalore",
    salary: "15-25 LPA",
    type: "Full-time",
    experience: "5-10 years",
    category: "IT & Software",
    description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications and leading technical initiatives.",
    requirements: ["5+ years of experience in Java/Python", "Experience with microservices architecture", "Strong problem-solving skills", "Excellent communication"],
    postedDate: "2024-01-15",
    featured: true,
  },
  {
    id: "2",
    title: "Product Manager",
    company: "Flipkart",
    location: "Bangalore",
    salary: "25-40 LPA",
    type: "Full-time",
    experience: "3-5 years",
    category: "IT & Software",
    description: "Join Flipkart as a Product Manager and drive product strategy for our e-commerce platform. Work with cross-functional teams to deliver exceptional user experiences.",
    requirements: ["3+ years in product management", "E-commerce experience preferred", "Data-driven decision making", "MBA preferred"],
    postedDate: "2024-01-14",
    featured: true,
  },
  {
    id: "3",
    title: "Financial Analyst",
    company: "HDFC Bank",
    location: "Mumbai",
    salary: "8-12 LPA",
    type: "Full-time",
    experience: "1-3 years",
    category: "Finance & Accounting",
    description: "HDFC Bank is hiring Financial Analysts to support our corporate banking division. Analyze financial data and provide insights for strategic decisions.",
    requirements: ["CA/CFA/MBA Finance", "Strong Excel skills", "Financial modeling experience", "Banking sector knowledge"],
    postedDate: "2024-01-13",
  },
  {
    id: "4",
    title: "UI/UX Designer",
    company: "Swiggy",
    location: "Bangalore",
    salary: "12-18 LPA",
    type: "Full-time",
    experience: "3-5 years",
    category: "Design & Creative",
    description: "Design intuitive and delightful user experiences for millions of Swiggy users. Work on mobile and web interfaces that solve real user problems.",
    requirements: ["Portfolio showcasing UI/UX work", "Figma/Sketch proficiency", "User research experience", "Mobile-first design thinking"],
    postedDate: "2024-01-12",
    featured: true,
  },
  {
    id: "5",
    title: "Data Scientist",
    company: "Infosys",
    location: "Hyderabad",
    salary: "18-28 LPA",
    type: "Full-time",
    experience: "3-5 years",
    category: "IT & Software",
    description: "Build machine learning models and data pipelines that drive business insights. Work with large datasets and cutting-edge AI technologies.",
    requirements: ["MS/PhD in CS or related field", "Python, R, SQL expertise", "Machine learning frameworks", "Big data technologies"],
    postedDate: "2024-01-11",
  },
  {
    id: "6",
    title: "Marketing Manager",
    company: "Zomato",
    location: "Gurgaon",
    salary: "15-22 LPA",
    type: "Full-time",
    experience: "5-10 years",
    category: "Marketing & Sales",
    description: "Lead marketing campaigns and brand initiatives for Zomato. Drive customer acquisition and engagement through innovative marketing strategies.",
    requirements: ["5+ years in digital marketing", "Brand management experience", "Performance marketing expertise", "Creative thinking"],
    postedDate: "2024-01-10",
  },
  {
    id: "7",
    title: "DevOps Engineer",
    company: "Amazon",
    location: "Hyderabad",
    salary: "20-35 LPA",
    type: "Full-time",
    experience: "3-5 years",
    category: "IT & Software",
    description: "Join Amazon Web Services and work on cloud infrastructure at scale. Build and maintain CI/CD pipelines and automation systems.",
    requirements: ["AWS certified", "Kubernetes, Docker experience", "Infrastructure as Code", "Linux administration"],
    postedDate: "2024-01-09",
    featured: true,
  },
  {
    id: "8",
    title: "HR Business Partner",
    company: "Tata Consultancy Services",
    location: "Mumbai",
    salary: "10-15 LPA",
    type: "Full-time",
    experience: "5-10 years",
    category: "HR & Recruitment",
    description: "Partner with business leaders to drive HR initiatives and talent management strategies. Lead employee engagement and organizational development programs.",
    requirements: ["MBA in HR", "5+ years HRBP experience", "Change management skills", "Strong stakeholder management"],
    postedDate: "2024-01-08",
  },
  {
    id: "9",
    title: "Frontend Developer",
    company: "Razorpay",
    location: "Bangalore",
    salary: "12-20 LPA",
    type: "Full-time",
    experience: "1-3 years",
    category: "IT & Software",
    description: "Build beautiful and performant web interfaces for Razorpay's payment products. Work with React and modern frontend technologies.",
    requirements: ["React.js expertise", "TypeScript knowledge", "CSS/Tailwind proficiency", "API integration experience"],
    postedDate: "2024-01-07",
  },
  {
    id: "10",
    title: "Mechanical Engineer",
    company: "Tata Motors",
    location: "Pune",
    salary: "8-14 LPA",
    type: "Full-time",
    experience: "1-3 years",
    category: "Engineering",
    description: "Design and develop automotive components for Tata Motors. Work on innovative vehicle designs and manufacturing processes.",
    requirements: ["B.Tech/M.Tech in Mechanical", "CAD software proficiency", "Automotive industry knowledge", "Quality standards understanding"],
    postedDate: "2024-01-06",
  },
  {
    id: "11",
    title: "Content Writer",
    company: "Byju's",
    location: "Remote",
    salary: "5-8 LPA",
    type: "Remote",
    experience: "0-1 years",
    category: "Education",
    description: "Create engaging educational content for students across India. Write curriculum-aligned content for K-12 and competitive exams.",
    requirements: ["Excellent English writing", "Education background preferred", "Research skills", "Creative storytelling"],
    postedDate: "2024-01-05",
  },
  {
    id: "12",
    title: "Sales Executive",
    company: "ICICI Prudential",
    location: "Delhi NCR",
    salary: "4-7 LPA + Incentives",
    type: "Full-time",
    experience: "Fresher",
    category: "Marketing & Sales",
    description: "Join our sales team and help customers find the right insurance products. Excellent growth opportunities with performance-based incentives.",
    requirements: ["Graduate in any discipline", "Good communication skills", "Sales aptitude", "Willingness to travel"],
    postedDate: "2024-01-04",
  },
];
