import { Job, TrendingItem } from "./types";

// Mock data for jobs
export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "UPSC Civil Services Examination 2025",
    titleHindi: "यूपीएससी सिविल सेवा परीक्षा 2025",
    organization: "Union Public Service Commission",
    organizationHindi: "संघ लोक सेवा आयोग",
    category: "latest-jobs",
    type: "upsc",
    state: "All India",
    qualification: "graduate",
    vacancies: 1056,
    salaryMin: 56100,
    salaryMax: 250000,
    ageMin: 21,
    ageMax: 32,
    applicationFee: {
      general: 100,
      obc: 100,
      sc_st: 0,
      women: 0,
    },
    importantDates: {
      notificationDate: "2025-02-14",
      startDate: "2025-02-14",
      lastDate: "2025-03-15",
      examDate: "2025-05-25",
    },
    links: {
      official: "https://upsc.gov.in",
      applyOnline: "https://upsconline.nic.in",
      notification: "#",
    },
    description: "UPSC invites applications for Civil Services Examination 2025 including IAS, IPS, IFS, and other Group A and B services.",
    descriptionHindi: "यूपीएससी सिविल सेवा परीक्षा 2025 के लिए आवेदन आमंत्रित करता है जिसमें आईएएस, आईपीएस, आईएफएस और अन्य ग्रुप ए और बी सेवाएं शामिल हैं।",
    highlights: [
      "1056 vacancies across various services",
      "Preliminary exam on 25th May 2025",
      "No fee for SC/ST and Women candidates",
    ],
    highlightsHindi: [
      "विभिन्न सेवाओं में 1056 रिक्तियां",
      "25 मई 2025 को प्रारंभिक परीक्षा",
      "SC/ST और महिला उम्मीदवारों के लिए कोई शुल्क नहीं",
    ],
    isHot: true,
    isFeatured: true,
    isPremium: false,
    createdAt: "2025-02-14",
    updatedAt: "2025-02-14",
  },
  {
    id: "2",
    title: "SSC CGL 2025 - Combined Graduate Level Examination",
    titleHindi: "एसएससी सीजीएल 2025 - संयुक्त स्नातक स्तर परीक्षा",
    organization: "Staff Selection Commission",
    organizationHindi: "कर्मचारी चयन आयोग",
    category: "latest-jobs",
    type: "ssc",
    state: "All India",
    qualification: "graduate",
    vacancies: 17727,
    salaryMin: 25500,
    salaryMax: 151100,
    ageMin: 18,
    ageMax: 32,
    applicationFee: {
      general: 100,
      obc: 100,
      sc_st: 0,
      women: 0,
    },
    importantDates: {
      notificationDate: "2025-03-01",
      startDate: "2025-03-01",
      lastDate: "2025-03-31",
      examDate: "2025-06-15",
    },
    links: {
      official: "https://ssc.nic.in",
      applyOnline: "https://ssc.nic.in",
      notification: "#",
    },
    description: "Staff Selection Commission invites applications for Combined Graduate Level Examination 2025 for various Group B and C posts.",
    descriptionHindi: "कर्मचारी चयन आयोग विभिन्न ग्रुप बी और सी पदों के लिए संयुक्त स्नातक स्तर परीक्षा 2025 के लिए आवेदन आमंत्रित करता है।",
    highlights: [
      "17,727 vacancies in various departments",
      "Computer Based Test in June 2025",
      "Posts include Tax Assistant, Auditor, and more",
    ],
    highlightsHindi: [
      "विभिन्न विभागों में 17,727 रिक्तियां",
      "जून 2025 में कंप्यूटर आधारित परीक्षा",
      "पदों में टैक्स असिस्टेंट, ऑडिटर और अधिक शामिल हैं",
    ],
    isHot: true,
    isFeatured: true,
    isPremium: false,
    createdAt: "2025-03-01",
    updatedAt: "2025-03-01",
  },
  {
    id: "3",
    title: "RRB NTPC 2025 - Railway Recruitment",
    titleHindi: "आरआरबी एनटीपीसी 2025 - रेलवे भर्ती",
    organization: "Railway Recruitment Boards",
    organizationHindi: "रेलवे भर्ती बोर्ड",
    category: "latest-jobs",
    type: "railway",
    state: "All India",
    qualification: "12th",
    vacancies: 35281,
    salaryMin: 19900,
    salaryMax: 92300,
    ageMin: 18,
    ageMax: 33,
    applicationFee: {
      general: 500,
      obc: 500,
      sc_st: 250,
      women: 250,
    },
    importantDates: {
      notificationDate: "2025-02-20",
      startDate: "2025-02-20",
      lastDate: "2025-03-25",
      examDate: "2025-07-01",
    },
    links: {
      official: "https://indianrailways.gov.in",
      applyOnline: "#",
      notification: "#",
    },
    description: "Railway Recruitment Boards invite online applications for Non-Technical Popular Categories (NTPC) posts for 12th and Graduate candidates.",
    descriptionHindi: "रेलवे भर्ती बोर्ड 12वीं और स्नातक उम्मीदवारों के लिए गैर-तकनीकी लोकप्रिय श्रेणी (एनटीपीसी) पदों के लिए ऑनलाइन आवेदन आमंत्रित करते हैं।",
    highlights: [
      "35,281 vacancies across all RRBs",
      "Posts include Station Master, Clerk, and more",
      "Age relaxation for reserved categories",
    ],
    highlightsHindi: [
      "सभी आरआरबी में 35,281 रिक्तियां",
      "पदों में स्टेशन मास्टर, क्लर्क और अधिक शामिल हैं",
      "आरक्षित श्रेणियों के लिए आयु में छूट",
    ],
    isHot: true,
    isFeatured: false,
    isPremium: false,
    createdAt: "2025-02-20",
    updatedAt: "2025-02-20",
  },
  {
    id: "4",
    title: "IBPS PO 2025 - Probationary Officer",
    titleHindi: "आईबीपीएस पीओ 2025 - परिवीक्षाधीन अधिकारी",
    organization: "Institute of Banking Personnel Selection",
    organizationHindi: "बैंकिंग कार्मिक चयन संस्थान",
    category: "latest-jobs",
    type: "bank",
    state: "All India",
    qualification: "graduate",
    vacancies: 4455,
    salaryMin: 36000,
    salaryMax: 63840,
    ageMin: 20,
    ageMax: 30,
    applicationFee: {
      general: 850,
      obc: 850,
      sc_st: 175,
      women: 175,
    },
    importantDates: {
      notificationDate: "2025-08-01",
      startDate: "2025-08-01",
      lastDate: "2025-08-21",
      examDate: "2025-10-15",
    },
    links: {
      official: "https://ibps.in",
      applyOnline: "#",
      notification: "#",
    },
    description: "IBPS invites applications for Probationary Officer posts in participating public sector banks across India.",
    descriptionHindi: "आईबीपीएस भारत भर के भाग लेने वाले सार्वजनिक क्षेत्र के बैंकों में परिवीक्षाधीन अधिकारी पदों के लिए आवेदन आमंत्रित करता है।",
    highlights: [
      "4,455 PO vacancies in PSU banks",
      "Prelims and Mains examination",
      "Starting salary approx. Rs. 36,000",
    ],
    highlightsHindi: [
      "PSU बैंकों में 4,455 पीओ रिक्तियां",
      "प्रारंभिक और मुख्य परीक्षा",
      "प्रारंभिक वेतन लगभग 36,000 रुपये",
    ],
    isHot: false,
    isFeatured: true,
    isPremium: false,
    createdAt: "2025-08-01",
    updatedAt: "2025-08-01",
  },
  {
    id: "5",
    title: "UP Police Constable 2025",
    titleHindi: "यूपी पुलिस कांस्टेबल 2025",
    organization: "Uttar Pradesh Police Recruitment Board",
    organizationHindi: "उत्तर प्रदेश पुलिस भर्ती बोर्ड",
    category: "latest-jobs",
    type: "police",
    state: "Uttar Pradesh",
    qualification: "12th",
    vacancies: 60244,
    salaryMin: 21700,
    salaryMax: 69100,
    ageMin: 18,
    ageMax: 25,
    applicationFee: {
      general: 400,
      obc: 400,
      sc_st: 400,
      women: 400,
    },
    importantDates: {
      notificationDate: "2025-04-01",
      startDate: "2025-04-01",
      lastDate: "2025-05-01",
      examDate: "2025-08-15",
    },
    links: {
      official: "https://uppbpb.gov.in",
      applyOnline: "#",
      notification: "#",
    },
    description: "UP Police Recruitment Board invites applications for Constable Civil Police and PAC positions.",
    descriptionHindi: "यूपी पुलिस भर्ती बोर्ड सिविल पुलिस और पीएसी कांस्टेबल पदों के लिए आवेदन आमंत्रित करता है।",
    highlights: [
      "60,244 Constable vacancies",
      "Written exam and physical test",
      "Domicile of UP required",
    ],
    highlightsHindi: [
      "60,244 कांस्टेबल रिक्तियां",
      "लिखित परीक्षा और शारीरिक परीक्षण",
      "यूपी का मूल निवासी आवश्यक",
    ],
    isHot: true,
    isFeatured: false,
    isPremium: false,
    createdAt: "2025-04-01",
    updatedAt: "2025-04-01",
  },
  {
    id: "6",
    title: "SSC CGL 2024 Admit Card Released",
    titleHindi: "एसएससी सीजीएल 2024 एडमिट कार्ड जारी",
    organization: "Staff Selection Commission",
    organizationHindi: "कर्मचारी चयन आयोग",
    category: "admit-card",
    type: "ssc",
    state: "All India",
    qualification: "graduate",
    vacancies: 14582,
    salaryMin: 25500,
    salaryMax: 151100,
    ageMin: 18,
    ageMax: 32,
    applicationFee: {
      general: 0,
      obc: 0,
      sc_st: 0,
      women: 0,
    },
    importantDates: {
      notificationDate: "2024-04-01",
      startDate: "2024-04-01",
      lastDate: "2024-05-01",
      examDate: "2025-03-10",
      admitCardDate: "2025-02-25",
    },
    links: {
      official: "https://ssc.nic.in",
      admitCard: "#",
      notification: "#",
    },
    description: "SSC CGL 2024 Tier-1 Admit Card has been released. Candidates can download from official website.",
    descriptionHindi: "एसएससी सीजीएल 2024 टियर-1 एडमिट कार्ड जारी किया गया है। उम्मीदवार आधिकारिक वेबसाइट से डाउनलोड कर सकते हैं।",
    highlights: [
      "Admit Card available for download",
      "Exam scheduled from 10th March 2025",
      "Check exam center and reporting time",
    ],
    highlightsHindi: [
      "एडमिट कार्ड डाउनलोड के लिए उपलब्ध",
      "10 मार्च 2025 से परीक्षा निर्धारित",
      "परीक्षा केंद्र और रिपोर्टिंग समय देखें",
    ],
    isHot: true,
    isFeatured: false,
    isPremium: false,
    createdAt: "2025-02-25",
    updatedAt: "2025-02-25",
  },
  {
    id: "7",
    title: "IBPS Clerk 2024 Final Result Declared",
    titleHindi: "आईबीपीएस क्लर्क 2024 अंतिम परिणाम घोषित",
    organization: "Institute of Banking Personnel Selection",
    organizationHindi: "बैंकिंग कार्मिक चयन संस्थान",
    category: "result",
    type: "bank",
    state: "All India",
    qualification: "graduate",
    vacancies: 6128,
    salaryMin: 22000,
    salaryMax: 47920,
    ageMin: 20,
    ageMax: 28,
    applicationFee: {
      general: 0,
      obc: 0,
      sc_st: 0,
      women: 0,
    },
    importantDates: {
      notificationDate: "2024-07-01",
      startDate: "2024-07-01",
      lastDate: "2024-07-21",
      resultDate: "2025-02-20",
    },
    links: {
      official: "https://ibps.in",
      result: "#",
      notification: "#",
    },
    description: "IBPS Clerk 2024 Final Result and Provisional Allotment have been released on the official website.",
    descriptionHindi: "आईबीपीएस क्लर्क 2024 अंतिम परिणाम और अनंतिम आवंटन आधिकारिक वेबसाइट पर जारी किया गया है।",
    highlights: [
      "Final result available now",
      "Check provisional allotment",
      "Document verification process to begin",
    ],
    highlightsHindi: [
      "अंतिम परिणाम अब उपलब्ध",
      "अनंतिम आवंटन देखें",
      "दस्तावेज़ सत्यापन प्रक्रिया शुरू होगी",
    ],
    isHot: true,
    isFeatured: false,
    isPremium: false,
    createdAt: "2025-02-20",
    updatedAt: "2025-02-20",
  },
  {
    id: "8",
    title: "RRB NTPC 2024 Answer Key Released",
    titleHindi: "आरआरबी एनटीपीसी 2024 उत्तर कुंजी जारी",
    organization: "Railway Recruitment Boards",
    organizationHindi: "रेलवे भर्ती बोर्ड",
    category: "answer-key",
    type: "railway",
    state: "All India",
    qualification: "12th",
    vacancies: 35281,
    salaryMin: 19900,
    salaryMax: 92300,
    ageMin: 18,
    ageMax: 33,
    applicationFee: {
      general: 0,
      obc: 0,
      sc_st: 0,
      women: 0,
    },
    importantDates: {
      notificationDate: "2024-02-20",
      startDate: "2024-02-20",
      lastDate: "2024-03-25",
      examDate: "2024-12-15",
    },
    links: {
      official: "https://indianrailways.gov.in",
      answerKey: "#",
      notification: "#",
    },
    description: "RRB NTPC CBT-1 Answer Key has been released. Candidates can raise objections till specified date.",
    descriptionHindi: "आरआरबी एनटीपीसी सीबीटी-1 उत्तर कुंजी जारी की गई है। उम्मीदवार निर्धारित तिथि तक आपत्ति दर्ज कर सकते हैं।",
    highlights: [
      "CBT-1 Answer Key available",
      "Object submission window open",
      "Fee Rs. 50 per objection",
    ],
    highlightsHindi: [
      "सीबीटी-1 उत्तर कुंजी उपलब्ध",
      "आपत्ति जमा करने की विंडो खुली",
      "प्रति आपत्ति 50 रुपये शुल्क",
    ],
    isHot: false,
    isFeatured: false,
    isPremium: false,
    createdAt: "2025-01-15",
    updatedAt: "2025-01-15",
  },
  {
    id: "9",
    title: "Indian Army Agniveer Recruitment 2025",
    titleHindi: "भारतीय सेना ��ग्निवीर भर्ती 2025",
    organization: "Indian Army",
    organizationHindi: "भारतीय सेना",
    category: "latest-jobs",
    type: "defence",
    state: "All India",
    qualification: "10th",
    vacancies: 46000,
    salaryMin: 30000,
    salaryMax: 40000,
    ageMin: 17,
    ageMax: 21,
    applicationFee: {
      general: 0,
      obc: 0,
      sc_st: 0,
      women: 0,
    },
    importantDates: {
      notificationDate: "2025-01-15",
      startDate: "2025-01-15",
      lastDate: "2025-02-15",
      examDate: "2025-04-01",
    },
    links: {
      official: "https://joinindianarmy.nic.in",
      applyOnline: "#",
      notification: "#",
    },
    description: "Indian Army invites applications for Agniveer recruitment in various categories including General Duty, Technical, and Clerk.",
    descriptionHindi: "भारतीय सेना विभिन्न श्रेणियों में अग्निवीर भर्ती के लिए आवेदन आमंत्रित करती है जिसमें जनरल ड्यूटी, तकनीकी और क्लर्क शामिल हैं।",
    highlights: [
      "46,000+ Agniveer vacancies",
      "4-year service engagement",
      "Monthly package Rs. 30,000 onwards",
    ],
    highlightsHindi: [
      "46,000+ अग्निवीर रिक्तियां",
      "4 वर्ष की सेवा सगाई",
      "मासिक पैकेज 30,000 रुपये से",
    ],
    isHot: true,
    isFeatured: true,
    isPremium: false,
    createdAt: "2025-01-15",
    updatedAt: "2025-01-15",
  },
  {
    id: "10",
    title: "Bihar TET 2025 - Teacher Eligibility Test",
    titleHindi: "बिहार टीईटी 2025 - शिक्षक पात्रता परीक्षा",
    organization: "Bihar School Examination Board",
    organizationHindi: "बिहार विद्यालय परीक्षा समिति",
    category: "latest-jobs",
    type: "teaching",
    state: "Bihar",
    qualification: "graduate",
    vacancies: 0,
    salaryMin: 0,
    salaryMax: 0,
    ageMin: 18,
    ageMax: 40,
    applicationFee: {
      general: 500,
      obc: 500,
      sc_st: 250,
      women: 250,
    },
    importantDates: {
      notificationDate: "2025-03-01",
      startDate: "2025-03-01",
      lastDate: "2025-03-31",
      examDate: "2025-06-15",
    },
    links: {
      official: "https://biharboardonline.bihar.gov.in",
      applyOnline: "#",
      notification: "#",
      syllabus: "#",
    },
    description: "Bihar School Examination Board invites applications for Teacher Eligibility Test 2025 for Paper 1 and Paper 2.",
    descriptionHindi: "बिहार विद्यालय परीक्षा समिति पेपर 1 और पेपर 2 के लिए शिक्षक पात्रता परीक्षा 2025 के लिए आवेदन आमंत्रित करती है।",
    highlights: [
      "Paper 1 for Class 1-5 teachers",
      "Paper 2 for Class 6-8 teachers",
      "Valid for 7 years from passing",
    ],
    highlightsHindi: [
      "कक्षा 1-5 शिक्षकों के लिए पेपर 1",
      "कक्षा 6-8 शिक्षकों के लिए पेपर 2",
      "उत्तीर्ण होने से 7 वर्षों के लिए वैध",
    ],
    isHot: false,
    isFeatured: false,
    isPremium: false,
    createdAt: "2025-03-01",
    updatedAt: "2025-03-01",
  },
];

// Trending news items for marquee
export const TRENDING_ITEMS: TrendingItem[] = [
  {
    id: "1",
    text: "UPSC CSE 2025 Notification Released - Apply Now!",
    textHindi: "यूपीएससी सीएसई 2025 अधिसूचना जारी - अभी आवेदन करें!",
    link: "/jobs/1",
    isNew: true,
  },
  {
    id: "2",
    text: "SSC CGL 2025 Registration Starts from 1st March",
    textHindi: "एसएससी सीजीएल 2025 पंजीकरण 1 मार्च से शुरू",
    link: "/jobs/2",
    isNew: true,
  },
  {
    id: "3",
    text: "RRB NTPC 2025 - 35,281 Vacancies Announced",
    textHindi: "आरआरबी एनटीपीसी 2025 - 35,281 रिक्तियां घोषित",
    link: "/jobs/3",
    isNew: true,
  },
  {
    id: "4",
    text: "UP Police 60,244 Constable Recruitment",
    textHindi: "यूपी पुलिस 60,244 कांस्टेबल भर्ती",
    link: "/jobs/5",
    isNew: false,
  },
  {
    id: "5",
    text: "Indian Army Agniveer Registration Open",
    textHindi: "भारतीय सेना अग्निवीर पंजीकरण खुला",
    link: "/jobs/9",
    isNew: false,
  },
];

// Statistics for homepage
export const SITE_STATS = {
  totalJobs: 15000,
  activeUsers: 500000,
  dailyUpdates: 50,
  successStories: 10000,
};

// Indian States
export const INDIAN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal", "Delhi", "Puducherry"
];
